
include: "rules/common.smk"
# Genome reference data acquisition (if user did not
# provide any genomic reference in configuration file)
include: "rules/reference/download_genome_annotation.smk"
include: "rules/reference/download_genome_sequence.smk"
include: "rules/indexing/bowtie2_index.smk"
include: "rules/indexing/samtools_faidx.smk"
include: "rules/reference/download_fastq_screen_index.smk"
include: "rules/reference/download_blacklist.smk"
# Trimming
include: "rules/trimming/fastp.smk"
# Library quality controls
include: "rules/trimming/fastq_screen.smk"
# Mapping
include: "rules/mapping/bowtie2_mapping.smk"
include: "rules/mapping/sambamba_samtools_filters.smk"
include: "rules/mapping/sambamba_markdup.smk"
include: "rules/mapping/deeptools_shift.smk"
include: "rules/mapping_qc/picard_collect_mutiple_metrics.smk"
include: "rules/mapping_qc/samtools.smk"
# Peak-Calling
include: "rules/peak-calling/macs2_callpeak.smk"
# Coverage
include: "rules/coverage/deeptools_bamcoverage.smk"
include: "rules/coverage/deeptools_matrix.smk"
include: "rules/coverage/deeptools_plot_heatmap.smk"
include: "rules/mapping_qc/deeptools_fingerprint.smk"
# QC aggregation
include: "rules/multiqc/multiqc_mapping.smk"
include: "rules/multiqc/multiqc_trimming.smk"



rule target:
    input:
        **targets(config),
